apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: 338476772910.dkr.ecr.ap-south-1.amazonaws.com/eks-app-deploy:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8089
# service type loadbalancers
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
