apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: demo1
        image: 338476772910.dkr.ecr.ap-south-1.amazonaws.com/rajeshecr:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
# service type loadbalancers
---
apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
  type: LoadBalancer
  selector:
    app: demo1
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
